"""Platform instructions per lab: environment setup and every GPU-only step the notebooks defer to the lab guide.
VERSION-SENSITIVE: every command below names a library or CLI whose flags change; verify against current docs on the delivery day."""
COMMON_SETUP = {
 "Databricks": [
  "Workspace: Premium tier, Unity Catalog enabled. Create catalog `northfield`, schema `llmops`, volume `labdata`; upload the `data/` folder to `/Volumes/northfield/llmops/labdata`.",
  "Cluster: single-node, Databricks Runtime ML **GPU** (latest LTS), node type per lab (NC24ads_A100_v4 for A100 labs, NC4as_T4_v3 for T4 labs, NC96ads_A100_v4 for L11). Auto-terminate 30 min.",
  "Init script (cluster-scoped) installs pinned versions: `pip install skl2onnx onnx onnxruntime-gpu httpx nbformat vllm sglang[all] transformers peft trl accelerate auto-awq optimum qdrant-client triton flash-attn --no-build-isolation`. Pin exact versions in the script after testing on the runtime; record them in the Verification Register.",
  "Secrets: model-hub token in a Databricks secret scope `northfield` key `hf_token`; export as `HF_TOKEN` in the notebook via `dbutils.secrets.get`.",
  "Notebooks: import the whole package folder, or upload `data/` to a Unity Catalog volume (the header also searches /Workspace and /Volumes for catalog_items.csv). Packages: labs install their own extras lazily and without a restart (L02/L08: onnx, onnxruntime, skl2onnx; L08: pyarrow; L03 GPU: httpx) via `ensure_packages()`. Optional: run `labs/L00_Setup/L00_setup.ipynb` once, or add the packages as cluster libraries, so nothing installs during a session. Rule after any manual %pip + restart: Run All from the top.",
 ],
 "Azure ML": [
  "Workspace with a GPU compute instance (Standard_NC24ads_A100_v4 for GPU labs, Standard_NC4as_T4_v3 or CPU for L09/L10). Idle shutdown 30 min.",
  "Environment: curated `AzureML-ACPT` (PyTorch + CUDA) image or a custom conda env with the same pip list as the Databricks init script.",
  "Upload `data/` to the workspace default datastore; set `DATA_DIR` in the notebook to the mounted path.",
  "For managed online endpoints (L03 alternative): build a custom container from the vLLM image and deploy with `azure-ai-ml` SDK v2 — `ManagedOnlineEndpoint` + `ManagedOnlineDeployment` on a `Standard_NC24ads_A100_v4` instance.",
 ],
}
STEPS = {
 "L01": {"Step 1": "GPU mode runs `nvidia-smi --query-gpu=... --format=csv` directly; confirm one A100 80GB appears. On Databricks the driver node is the only node on a single-node cluster.",
         "Step 3 worked example": "Dense 31B bf16: weights 62 GB; KV = 2×60×8×128×2 B×8192×8 = 16.1 GB; total ×1.1 = 85.9 GB → 2× A100-80GB at 90 % usable. Have participants reproduce this on paper before running the cell."},
 "L02": {"Step 4": "`hf download google/gemma-4-e4b-it --local-dir /local_disk0/gemma4` (verify model id). AWQ: `from awq import AutoAWQForCausalLM` → `quantize(tokenizer, quant_config={'w_bit':4,'q_group_size':128,'zero_point':True,'version':'GEMM'})` → `save_quantized`. GGUF: clone llama.cpp, `python convert_hf_to_gguf.py /local_disk0/gemma4 --outtype q4_k_m --outfile gemma4.gguf` (script name and `--outtype` values are version-sensitive). Record `ls -l` sizes into `sizes`.",
         "Step 5": "Serve each artefact: safetensors and AWQ via `vllm serve <path> --quantization awq` (for AWQ); GGUF via `llama-server -m gemma4.gguf`. Run the 50 eval prompts through each with temperature 0 and compute exact-match with the provided function."},
 "L03": {"Step 4": "Start servers on separate ports (one at a time to keep GPU memory free): vLLM `vllm serve google/gemma-4-e4b-it --port 8001`; SGLang `python -m sglang.launch_server --model-path google/gemma-4-e4b-it --port 8002`; TensorRT-LLM: build the engine (`trtllm-build` or the PyTorch backend `trtllm-serve` — the CLI surface changed across 2025–26; use whichever the installed version documents) and serve on 8003. `pip install httpx` for the harness client.",
         "Step 5": "Stopwatch from process start to first successful `/v1/models` response = cold start. For TensorRT-LLM record engine-build time separately."},
 "L04": {"Step 2": "`from sentence_transformers import SentenceTransformer; m = SentenceTransformer('<checkpoint agreed with the recommendation team>'); E = m.encode(list(cat.title), normalize_embeddings=True, batch_size=256)`.",
         "Step 4": "Qdrant: `docker run -p 6333:6333 qdrant/qdrant` on the driver (or Qdrant Cloud). `client.recreate_collection('northfield', vectors_config=VectorParams(size=E.shape[1], distance=Distance.COSINE))`; upsert points; `client.search(...limit=10)`. Databricks Vector Search alternative: create a Delta table with the embedding column, `VectorSearchClient().create_delta_sync_index(...)`, then `index.similarity_search(...)`. Both APIs are version-sensitive."},
 "L05": {"Step 4": "`model = AutoModelForCausalLM.from_pretrained(id, torch_dtype=torch.bfloat16, attn_implementation='eager').cuda()`; wrap 32 `generate` tokens in `torch.profiler.profile(activities=[CPU,CUDA])`; `prof.export_chrome_trace('eager.json')`; repeat with `attn_implementation='flash_attention_2'` (requires `flash-attn` built for the runtime's torch/CUDA — check `import flash_attn` first). Compare attention kernel share in `prof.key_averages()`.",
         "Step 5": "Kernel skeleton: `@triton.jit def fused_rmsnorm_residual(x_ptr, r_ptr, w_ptr, out_ptr, n_cols, eps, BLOCK: tl.constexpr)` — load a row of x and residual, add, compute rsqrt(mean(x²)+eps), multiply by weight, store. Compare with `torch` reference (`allclose atol=1e-3`) and time with `triton.testing.do_bench`."},
 "L06": {"Step 5": "vLLM MoE serving: `vllm serve google/gemma-4-26b-a4b-it` (single A100-80GB fits bf16 per L01) and `vllm serve nvidia/<nemotron-3-nano id> --trust-remote-code`; for multi-GPU expert parallel add `--tensor-parallel-size N` (and `--enable-expert-parallel` where supported — flag names are version-sensitive). Dense baseline: `vllm serve google/gemma-4-31b-it` needs 2× A100 (TP=2) or int4 (`--quantization awq`) on one. Run the L03 harness at concurrency 8 and 32; record `nvidia-smi` memory."},
 "L07": {"Step 4": "`from peft import LoraConfig; cfg = LoraConfig(r=16, lora_alpha=32, lora_dropout=0.05, target_modules=[…q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj — confirm names from model.named_modules()], task_type='CAUSAL_LM')`. `from trl import SFTTrainer, SFTConfig`; format each row as prompt + target JSON; 3 epochs, lr 2e-4, bf16. `mlflow.autolog()` before training. Signatures of `SFTTrainer`/`SFTConfig` changed across trl versions — verify.",
         "Step 5": "`predict_fn = lambda p: tokenizer.decode(model.generate(**tokenizer(p, return_tensors='pt').to('cuda'), max_new_tokens=64, do_sample=False)[0][input_len:], skip_special_tokens=True)`; `tuned = evaluate(predict_fn, evalset)`.",
         "Step 6": "`model = model.merge_and_unload()`; `mlflow.set_registry_uri('databricks-uc')`; `mlflow.transformers.log_model(transformers_model={'model': model, 'tokenizer': tokenizer}, artifact_path='model', registered_model_name='northfield.llmops.gemma4_e4b_attr')`.",
         "Step 7": "Databricks Model Serving: create a GPU endpoint (GPU_MEDIUM or per pricing sheet) from the UC model version; or `vllm serve /local_disk0/merged`. Run 20 golden prompts, one malformed prompt (expect HTTP 4xx, not 5xx), and the L03 harness for p95."},
 "L08": {"Step 2": "`AutoModelForSequenceClassification.from_pretrained('roberta-base', num_labels=8)` (or the team's domain checkpoint); `Trainer` 3 epochs, lr 2e-5, max_length 64. Export: `optimum-cli export onnx --model <dir> --task text-classification /tmp/roberta_onnx`. In the Spark UDF replace the sklearn session with `onnxruntime.InferenceSession(path, providers=['TensorrtExecutionProvider','CUDAExecutionProvider'])` on GPU workers; tokenise in the UDF.",
         "Step 5": "Multi-node: cluster with 2–4 T4 workers; set `spark.task.resource.gpu.amount 1`; repartition to workers×2. Compare items/s vs single node; compute cost per million from measured rate × VM $/hr (include all workers)."},
 "L09": {"Step 5": "Azure ML: package `harness()`+`gate()` as `eval_gate.py` that exits 1 on failure; component YAML `type: command`, `command: python eval_gate.py --candidate ${{inputs.candidate}} --golden ${{inputs.golden}}`; pipeline: train → eval_gate → register (`azure-ai-ml` `@pipeline` decorator). Submit for both candidates; the regressed run must fail at eval_gate. Databricks: Job with task 1 = this notebook, task 2 = register + set alias `champion` (`MlflowClient().set_registered_model_alias`), depends-on task 1."},
 "L10": {"Step 5": "Databricks: enable inference tables on the L07 endpoint; `from databricks.sdk.service.catalog import MonitorInferenceLog` (or `databricks.lakehouse_monitoring` — the API moved; verify) — create a monitor with `baseline_table` = week-1 snapshot, granularity 1 day. Azure ML: on the deployment, enable data collection; create a model monitor with the Data drift signal and a baseline dataset; set alert notification. Screenshot the drift chart."},
 "L11": {"Step 4": "`from ray.util.spark import setup_ray_cluster; setup_ray_cluster(num_worker_nodes=1, num_gpus_worker_node=4)`; `ray.init()`; `vllm serve google/gemma-4-31b-it --tensor-parallel-size 4 --distributed-executor-backend ray`. Run L03 harness at concurrency 32. Simulate loss: `ray.kill` a worker actor or restart the worker VM from the cluster UI; record seconds until `/v1/models` answers again. Flag names are version-sensitive."},
 "L12": {"Note": "No GPU. On Databricks the same notebook runs on a small CPU cluster; the decision record can be written to a Delta table `northfield.llmops.experiment_decisions` instead of /tmp."},
 "L14": {"Note": "No GPU. Production equivalents: Microsoft Presidio for PII (NER-based), Guardrails AI / NeMo Guardrails for rails, provider structured outputs (JSON schema / tool calling) for format enforcement. Wire the three gate functions around the served endpoint from L07."},
 "L15": {"Step 6": "Embeddings: `SentenceTransformer('<agreed checkpoint>').encode(sops.text, normalize_embeddings=True)`. Judge: `from ragas import evaluate; from ragas.metrics import faithfulness, answer_relevancy` on a Dataset with question/contexts/answer columns; set the judge LLM to a different provider/model than the serving model. APIs are version-sensitive."},
 "L16": {"Note": "Trace store on the cluster: MLflow Tracing (`mlflow.trace`) or LangSmith / OpenTelemetry exporters into a Delta table `northfield.llmops.traces` with the same columns as trace_log.jsonl. Replay = the same generate() call with `contexts` supplied instead of retrieved."},
 "L17": {"Note": "Replace PLACEHOLDER rates with the provider's current price list and `measured_tok_s` with the L03 harness result at target concurrency on the chosen SKU; keep the formulas."},
 "L13": {"Step 6": "On Databricks the notebook writes `format('delta')` automatically. Save as a table instead: `cat3.write.mode('overwrite').saveAsTable('northfield.llmops.catalog_clean')`; then `DESCRIBE HISTORY northfield.llmops.catalog_clean` to show versioning."},
}
TROUBLESHOOT = [
 ("OOM at model load", "Check L01 memory-fit; add `--max-model-len 4096` or `--gpu-memory-utilization 0.85` to vLLM; use int4 (AWQ) for 31B on one A100."),
 ("`flash_attn` import error", "Wheel/torch/CUDA mismatch. Install the wheel matching the runtime's torch; if unavailable, use `attn_implementation='sdpa'` and note it in the Verification Register."),
 ("Model download 403/401", "HF token missing or gated model licence not accepted on the hub account."),
 ("Spark UDF slow", "Arrow batch too small (`spark.sql.execution.arrow.maxRecordsPerBatch`), or session recreated per call — check the module-level cache."),
 ("`#NAME?` in workbook", "Opened in a viewer that cannot evaluate; open in Excel/LibreOffice and recalculate."),
 ("Notebook says SMOKE on a GPU node", "`nvidia-smi` not on PATH in the kernel; set `os.environ['LAB_MODE']='GPU'` in the header cell."),
]
